local TenderManager = {}

function TenderManager.ReadyForFish(tenderState, linkedBoat)
	-- create function to locate the correct Boat the Tender is linked to
	-- create function to attempt to add fish within a 5 second timeframe
	-- create function to move the Tender to the Port/Original position
	-- ReadyToOffload(state, boat)
end

function TenderManager.ReadyToOffload(tenderState, linkedBoat)
	-- create function to attempt to remove fish within a 5 second timeframe
	-- create function to move the Tender to the Port/Original position
	-- ReadyForFish(tenderState, linkedBoat)
end

return TenderManager
